name: Test ojete
description: Ojete

runs:
  using: composite
  steps:
    - name: Echo
      id: echo
      shell: bash
      run: |
       echo "OJETE MORENO"
       echo "Nuestro secreto es: $super_secret"
       export culo=$super_secret
       echo $culo | shasum
       echo $super_secret | shasum
       echo "hollalaala $culo wksksjksjs"
       env